name = "linkgrove"
main = "src/index.js"
compatibility_date = "2026-02-24"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "public"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "linkgrove"
database_id = "4ed0165b-a38a-4a20-8a85-1d58fe051673"

[ai]
binding = "AI"
